apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: webui
    env: production
    tier: frontend
    version-dockercoins: "1.0"
    version-webui: "2.0"
  type: ClusterIP
