apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hasher
    env: production
    tier: backend
    version-dockercoins: "1.0"
    version-hasher: "0.1"
  type: ClusterIP  
