apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasher
      env: production
      tier: backend
      version-dockercoins: "1.0"
      version-hasher: "0.1"
  template:
    metadata:
      labels:
        app: hasher
        env: production
        tier: backend
        version-dockercoins: "1.0"
        version-hasher: "0.1"
    spec:
      containers:
        - 
          args:
            - hasher.rb
          command:
            - ruby
          image: dockercoins-hasher:testing
          name: hasher-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            -
              mountPath: /src/hasher.rb
              name: hasher-volume
              readOnly: true
              subPath: hasher.rb
          workingDir: /src/
      volumes:
        -
          configMap:
            defaultMode: 0400
            items:
              -
                key: hasher.rb
                mode: 0400
                path: hasher.rb
            name: hasher-cm
          name: hasher-volume
